name: release
on:
  # dispatch from tagpr.yml workflow
  workflow_dispatch:
    inputs:
      tag_version:
        required: true
        description: Version tag

jobs:
  release-job:
    name: Release job.
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Get PHP version
        id: php-version
        run: |
          echo "PHP_VERSION=`jq -r '.config.platform.php' composer.json`" >> $GITHUB_ENV

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Run composer archive
        run: |
          composer archive --format zip --file composer

      - name: Upload Release Asset
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.payload.inputs.tag_version
            });
            const filePath = path.join(path.resolve(process.env.GITHUB_WORKSPACE), 'composer.zip');
            const fileContent = fs.readFileSync(filePath);
            await github.rest.repos.uploadReleaseAsset({
              url: release.data.upload_url,
              headers: {
                'content-type': 'application/octet-stream',
                'content-length': fileContent.length,
              },
              name: 'composer.zip',
              data: fileContent,
            });

      - name: Submit packages
        run: |
          curl \
          -XPOST \
          -H'content-type:application/json' \
          'https://packagist.org/api/update-package?username=litalico-engineering@r2&apiToken=${{ secrets.PACKAGIST_TOKEN }}' \
          -d'{"repository":{"url":"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"}}'
